s = set()

num = int(input("Enter number : "))
s.add(num)

num = int(input("Enter number : "))
s.add(num)
num = int(input("Enter number : "))
s.add(num)
num = int(input("Enter number : "))
s.add(num)
num = int(input("Enter number : "))
s.add(num)
num = int(input("Enter number : "))
s.add(num)
num = int(input("Enter number : "))
s.add(num)
print(s)